# ============================================================
# FARMACOV BACKEND application.properties
# ============================================================
# IMPORTANTE: este archivo NO se sube a git
# ------------------------------------------------------------
# BASE DE DATOS
# ------------------------------------------------------------
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=8x2hierrommv
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3307/FARMACOV


#CAMBIA POR EL NOMBRE DE TU BASE DE DATOS LOCAL!!!!

# ------------------------------------------------------------
# HIBERNATE
# ------------------------------------------------------------
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true

# ------------------------------------------------------------
# FIREBASE
# ------------------------------------------------------------
firebase.credentials=farmacovauth-firebase-adminsdk-fbsvc-7b4f17c372.json


# ------------------------------------------------------------
# Swagger/openapi
# swagger tambien en produccion
quarkus.swagger-ui.always-include=true
# ruta donde vive
quarkus.swagger-ui.path=/swagger-ui
#tituo
quarkus.smallrye-openapi.info-title=Farmacov API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description= Portal analisis farmacos

quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=bearerAuth
quarkus.smallrye-openapi.jwt-security-scheme-value=bearer

# ------------------------------------------------------------
# CORS
# ------------------------------------------------------------
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Authorization,Content-Type,Accept
quarkus.http.cors.access-control-allow-credentials=true

# ------------------------------------------------------------
# TESTS
# ------------------------------------------------------------
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:farmacovtest
%test.quarkus.datasource.jdbc.driver=org.h2.Driver
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
